// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5a2rHT2TWK3CsrExJ48r0vken-5xsMc',
    appId: '1:599590060410:web:5acc4f34e2d1e90db6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    authDomain: 'flutterapplication1-abdad.firebaseapp.com',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSUS9pOxwgdj6gXJPJMopbbc8gNqMis0',
    appId: '1:599590060410:android:2adbacb33438a204b6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkP6z1PcWxBxjRBbWcEC2bUjqqTrWkPv8',
    appId: '1:599590060410:ios:9307fa646bae1c1ab6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkP6z1PcWxBxjRBbWcEC2bUjqqTrWkPv8',
    appId: '1:599590060410:ios:9307fa646bae1c1ab6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI5a2rHT2TWK3CsrExJ48r0vken-5xsMc',
    appId: '1:599590060410:web:7e7e67760ab74c07b6d6c3',
    messagingSenderId: '599590060410',
    projectId: 'flutterapplication1-abdad',
    authDomain: 'flutterapplication1-abdad.firebaseapp.com',
    storageBucket: 'flutterapplication1-abdad.firebasestorage.app',
  );
}
